# Interactive Plotting with Plotly and Cufflinks

## Installing and importing required Libraries/Packages

Install plotly and cufflinks with:
- pip install cufflinks

__Required Action__: cufflinks is __incompatible with Numpy version 2.x__. In case you have installed Numpy 2.x please __downgrade__ with:

conda install numpy==1.26.4

__Recommendation__: matplotlib 3.8 may be more stable in conjunction with cufflinks than matplotlib 3.9. You may downgrade with:

conda install matplotlib==3.8

__Recommendation__: pandas 1.x may be more stable in conjunction with cufflinks than pandas 2.x. You may downgrade with:

conda install pandas==1.5.3

## Creating Offline Graphs in Jupyter Notebooks

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cufflinks as cf
import warnings
warnings.filterwarnings("ignore")

-------------------------------------

__Please check your installed numpy version__:

In [3]:
np.__version__ # cufflinks won´t work with numpy 2.x (see above)

'1.26.4'

__Please check your installed matplotlib version__:

In [2]:
import matplotlib # cufflinks tends to be more stable with matplotlib 3.8 (optional)
matplotlib.__version__

'3.9.0'

__Please check your installed pandas version__:

In [4]:
pd.__version__ # 1.x works best with cufflinks

'2.2.2'

----------------------------------

In [5]:
stocks = pd.read_csv("stocks.csv", header = [0,1], index_col= [0], parse_dates= [0]).Close

In [6]:
stocks.head()

Ticker          AAPL         BA        DIS        IBM         KO       MSFT
Date
2010-01-04  6.424606  43.777550  27.475880  73.283325  17.692520  23.211439
2010-01-05  6.435713  45.211346  27.407339  72.398079  17.478497  23.218941
2010-01-06  6.333344  46.582806  27.261690  71.927765  17.472292  23.076450
2010-01-07  6.321638  48.468555  27.270256  71.678787  17.428860  22.836464
2010-01-08  6.363666  48.001011  27.313093  72.398079  17.106276  22.993952

In [7]:
norm = stocks.div(stocks.iloc[0, :]).mul(100)

In [8]:
norm

Ticker,AAPL,BA,DIS,IBM,KO,MSFT
Date,,,,,,
2010-01-04,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2010-01-05,100.172889,103.275185,99.750543,98.792022,98.790316,100.032319
2010-01-06,98.579495,106.407978,99.220445,98.150247,98.755247,99.418439
2010-01-07,98.397284,110.715551,99.251621,97.810501,98.509763,98.384524
2010-01-08,99.051455,109.647550,99.407529,98.792022,96.686483,99.063017
...,...,...,...,...,...,...
2019-01-30,612.011111,860.592495,389.491793,129.941693,221.336968,430.323665
2019-01-31,616.418203,855.931228,394.407715,129.980338,222.585634,422.435735
2019-02-01,616.714550,859.948787,393.629639,129.670949,225.221648,415.761201
2019-02-04,634.232240,881.190573,395.397991,130.724899,227.765272,427.734762
2019-02-05,645.083804,910.445170,398.439544,131.073037,227.811521,433.721641

In [9]:
cf.set_config_file(offline = True)

In [10]:
cf.go_offline()

In [11]:
norm.iplot()

## Interactive Price Charts with Plotly

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cufflinks as cf
import warnings
warnings.filterwarnings("ignore")

In [13]:
cf.set_config_file(offline = True)

In [14]:
stocks = pd.read_csv("stocks.csv", header = [0,1], index_col= [0], parse_dates= [0]).Close

In [15]:
stocks.head()

Ticker          AAPL         BA        DIS        IBM         KO       MSFT
Date
2010-01-04  6.424606  43.777550  27.475880  73.283325  17.692520  23.211439
2010-01-05  6.435713  45.211346  27.407339  72.398079  17.478497  23.218941
2010-01-06  6.333344  46.582806  27.261690  71.927765  17.472292  23.076450
2010-01-07  6.321638  48.468555  27.270256  71.678787  17.428860  22.836464
2010-01-08  6.363666  48.001011  27.313093  72.398079  17.106276  22.993952

In [16]:
norm = stocks.div(stocks.iloc[0, :]).mul(100)

In [17]:
norm

Ticker,AAPL,BA,DIS,IBM,KO,MSFT
Date,,,,,,
2010-01-04,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2010-01-05,100.172889,103.275185,99.750543,98.792022,98.790316,100.032319
2010-01-06,98.579495,106.407978,99.220445,98.150247,98.755247,99.418439
2010-01-07,98.397284,110.715551,99.251621,97.810501,98.509763,98.384524
2010-01-08,99.051455,109.647550,99.407529,98.792022,96.686483,99.063017
...,...,...,...,...,...,...
2019-01-30,612.011111,860.592495,389.491793,129.941693,221.336968,430.323665
2019-01-31,616.418203,855.931228,394.407715,129.980338,222.585634,422.435735
2019-02-01,616.714550,859.948787,393.629639,129.670949,225.221648,415.761201
2019-02-04,634.232240,881.190573,395.397991,130.724899,227.765272,427.734762
2019-02-05,645.083804,910.445170,398.439544,131.073037,227.811521,433.721641

In [18]:
norm.iplot()

## Customizing Plotly Charts

In [19]:
norm.head()

Ticker,AAPL,BA,DIS,IBM,KO,MSFT
Date,,,,,,
2010-01-04,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2010-01-05,100.172889,103.275185,99.750543,98.792022,98.790316,100.032319
2010-01-06,98.579495,106.407978,99.220445,98.150247,98.755247,99.418439
2010-01-07,98.397284,110.715551,99.251621,97.810501,98.509763,98.384524
2010-01-08,99.051455,109.647550,99.407529,98.792022,96.686483,99.063017

In [20]:
norm.iplot(kind = "line", fill = True)

In [21]:
cf.colors.scales()

In [22]:
norm.iplot(kind = "line", fill = True, colorscale= "reds")

In [23]:
cf.getThemes()

['ggplot', 'pearl', 'solar', 'space', 'white', 'polar', 'henanigans']

In [24]:
norm.iplot(kind = "line", fill = True, colorscale= "rdylbu", theme= "solar")

In [25]:
norm.iplot(kind = "line", fill = True, colorscale= "rdylbu", theme= "solar", 
             title= "US Stocks", xTitle= "Time", yTitle= "Stock Price")

In [27]:
import numpy as np
import pandas as pd

# Monkey patch for cufflinks expecting pd.np
pd.np = np  

# Your plotting code
norm[["AAPL", "BA"]].iplot(
    kind="spread",
    fill=True,
    colorscale="set3",
    theme="solar",
    title="AAPL vs. BA",
    xTitle="Time",
    yTitle="Stock Price"
)

## Creating Interactive Histograms

In [28]:
stocks.head()

Ticker          AAPL         BA        DIS        IBM         KO       MSFT
Date
2010-01-04  6.424606  43.777550  27.475880  73.283325  17.692520  23.211439
2010-01-05  6.435713  45.211346  27.407339  72.398079  17.478497  23.218941
2010-01-06  6.333344  46.582806  27.261690  71.927765  17.472292  23.076450
2010-01-07  6.321638  48.468555  27.270256  71.678787  17.428860  22.836464
2010-01-08  6.363666  48.001011  27.313093  72.398079  17.106276  22.993952

In [29]:
ret = stocks.pct_change().dropna()

In [30]:
ret.head()

Ticker          AAPL        BA       DIS       IBM        KO      MSFT
Date
2010-01-05  0.001729  0.032752 -0.002495 -0.012080 -0.012097  0.000323
2010-01-06 -0.015906  0.030334 -0.005314 -0.006496 -0.000355 -0.006137
2010-01-07 -0.001848  0.040482  0.000314 -0.003461 -0.002486 -0.010400
2010-01-08  0.006648 -0.009646  0.001571  0.010035 -0.018509  0.006896
2010-01-11 -0.008822 -0.011851 -0.016311 -0.010470  0.020308 -0.012720

In [31]:
ret.iplot(kind = "histogram", bins = (-0.15, 0.1, 0.001), histnorm= "percent")

## Interactive Candlestick and OHLC Charts

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cufflinks as cf
import warnings
warnings.filterwarnings("ignore")

In [33]:
stocks = pd.read_csv("stocks.csv", header = [0,1], index_col= [0], parse_dates= [0])

In [34]:
stocks.head()

Price          Close                                                         \
Ticker          AAPL         BA        DIS        IBM         KO       MSFT
Date
2010-01-04  6.424606  43.777550  27.475880  73.283325  17.692520  23.211439
2010-01-05  6.435713  45.211346  27.407339  72.398079  17.478497  23.218941
2010-01-06  6.333344  46.582806  27.261690  71.927765  17.472292  23.076450
2010-01-07  6.321638  48.468555  27.270256  71.678787  17.428860  22.836464
2010-01-08  6.363666  48.001011  27.313093  72.398079  17.106276  22.993952

Price           High                                   ...       Open  \
Ticker          AAPL         BA        DIS        IBM  ...        DIS
Date                                                   ...
2010-01-04  6.439316  43.941189  28.058468  73.571036  ...  27.844281
2010-01-05  6.472038  45.413946  27.552986  72.951370  ...  27.475879
2010-01-06  6.461230  46.746448  27.415905  72.752169  ...  27.330230
2010-01-07  6.364267  48.554272  27.295959  72.066088  ...  27.218852
2010-01-08  6.364266  48.141274  27.364499  72.436807  ...  27.124609

Price                                           Volume                      \
Ticker            IBM         KO       MSFT       AAPL        BA       DIS
Date
2010-01-04  72.580646  17.729741  22.963951  493729600   6186700  13700400
2010-01-05  72.857308  17.633585  23.136445  601904800   8867800  10307700
2010-01-06  72.304001  17.478494  23.158946  552160000   8836500  10709500
2010-01-07  71.855838  17.472286  22.971457  477131200  14379100   8202100
2010-01-08  71.413221  17.202430  22.708965  447610800   7146600   7657500

Price
Ticker          IBM        KO      MSFT
Date
2010-01-04  6438444  13870400  38409100
2010-01-05  7156104  23172400  49749600
2010-01-06  5863144  19264600  58182400
2010-01-07  6109268  13234600  50559700
2010-01-08  4390271  28712400  51197400

[5 rows x 30 columns]

In [35]:
aapl = stocks.swaplevel(axis = 1).AAPL

In [36]:
aapl.head()

Price          Close      High       Low      Open     Volume
Date
2010-01-04  6.424606  6.439316  6.375673  6.407194  493729600
2010-01-05  6.435713  6.472038  6.401790  6.442318  601904800
2010-01-06  6.333344  6.461230  6.326739  6.435713  552160000
2010-01-07  6.321638  6.364267  6.275707  6.356762  477131200
2010-01-08  6.363666  6.364266  6.276008  6.313232  447610800

In [37]:
aapl.loc["5-2017":"9-2017"].iplot(kind= "candle")

## Adding SMA and Bollinger Bands

In [38]:
aapl.head()

Price          Close      High       Low      Open     Volume
Date
2010-01-04  6.424606  6.439316  6.375673  6.407194  493729600
2010-01-05  6.435713  6.472038  6.401790  6.442318  601904800
2010-01-06  6.333344  6.461230  6.326739  6.435713  552160000
2010-01-07  6.321638  6.364267  6.275707  6.356762  477131200
2010-01-08  6.363666  6.364266  6.276008  6.313232  447610800

In [39]:
qf = cf.QuantFig(df = aapl.loc["5-2017":"9-2017"])

In [40]:
type(qf)

cufflinks.quant_figure.QuantFig

In [41]:
qf.iplot(title = "AAPL", name = "AAPL")

In [42]:
qf.add_sma(periods = 20)

In [43]:
qf.iplot(title = "AAPL", name = "AAPL")

In [44]:
qf.add_bollinger_bands(periods = 20, boll_std= 2)

In [45]:
qf.iplot(title = "AAPL", name = "AAPL")

## Adding more Technical Indicators

In [46]:
qf = cf.QuantFig(df = aapl.loc["5-2017":"9-2017"])

In [47]:
qf.add_bollinger_bands(periods = 20, boll_std= 2)
qf.add_sma(periods = 20)
qf.add_macd()
qf.add_volume()
qf.add_dmi()

In [48]:
qf.iplot(title = "AAPL", name = "AAPL")